### PR TITLE
Proposed InfBallSec committee position

### PR DESCRIPTION
**Pull request by kimbethstonehouse**
The InfBall has previously been left until the last minute to organise as other committee members are busy with other responsibilities. A dedicated committee member will ensure that planning the ball starts in a timely fashion.

### CODE REVIEW

**Comment by mojavad** [comment]
So, following up on our talk in person: 

I don't really think having a InfBallSec is the way to go. I understand that planning and organising InfBall takes a massive amount of time. I think that there needs to be earlier planning for InfBall in future years (starting the committee in Nov/Dec instead of Jan, and looking for venues before the Christmas break), and there needs to be deadlines set in advance to avoid things piling up. 

That being said, I think that the Social Sec is, and should ultimately, be responsible for Infball, and that delegation should be done more accordingly, and the time spent for planning should be increased next year.

I'll try to highlight these in the handover notes for the next committee along with any other feedback you may have from this year.

**Comment by pkage** [comment]
As much as having this as it's own committee position is tempting, I think this should be a Social Sec-appointed position. Having an election for an infballsec seems gratuitous.

With that said, I think we need to codify the timeline for planning InfBall in the constitution (e.g. planned meetings, appointment, etc) as every year infball organization happens much too late.

**Comment by qaisjp** [comment]
Agreed, this is the job of the social sec. Last year the social sec was supposed to run the first Informatics Ball, and we appointed one after the AGM because nobody ran for election. But in the end he had to step down from that responsibility.

@mojavad — when Elizabeth was elected as social sec at the start of your year, I told her she should get the Informatics Ball venue booked before term starts. And if not by September, by November, the very latest. Last year we were very late in getting things locked in for January, and I think things were even later this year. Please can you consider passing this on in your notes?

**Comment by kimbethstonehouse** [comment]
The current system needs to change in some way to prevent this from happening again, so if the committee feels it's better for the ball to remain the social sec's responsibility, then I agree with Patrick - a timeline needs to be specified and stuck to.

@mojavad - if you're putting together handover notes, I'd be happy to make some suggestions for a proposed timeline based on my experiences this year.

**Comment by JMaio** [comment]
"It will be the SocialSec's responsibility to form a committee to organise InfBall, ideally prior to the end of the first semester of the academic year [...]"
Specifying and adhering to a timeline is a good idea (we can work out final details later)

**Comment by qaisjp** [comment]
> Specifying and adhering to a timeline is a good idea (we can work out final details later)

Do you think that maybe adding the timeline to the constitution gives future committees less flexibility in what they want to do?

**Comment by JMaio** [comment]
As suggested by @kimbethstonehouse - a proposed timeline, which, in conjunction with explicit assignment of InfBall responsibilities to SocialSec (forming an InfBall committee) should mean things end up going more smoothly in coming years.

**Comment by AngusP** [comment]
The constitution does allow for the committee to add additional positions already, perhaps adding an InfBall position informally at first would be a good way to see if it sticks?

>  df75ca6 **§2.9**
>The committee may find it helpful to appoint members to additional positions
> on the committee after the elections. These must be co-opted onto the committee by a two
> third majority of the current committee.

**Comment by lollobaldo** [comment]
Quite surprised nobody tagged me in this so Ive only just seen it but @kimbethstonehouse I am the new social sec so feel free to text me anytime if you have any suggestion or things to watch out for or really anything I should know

**Comment by qaisjp** [comment]
@lollobaldo start finding and booking a venue now 😅

**Pull request closed without merging**
