### PR TITLE
cleanup of 'general' section

### PR DESCRIPTION
**Pull request by JMaio**

### CODE REVIEW

**Review by himmelmaus — APPROVED** [review]

**Comment by himmelmaus** [comment]
AFAIK we need to have a vote on any change in the language of the constitution, even for things like typo corrections so will need to wait til the EGM for this. @qaisjp is that right?

**Comment by qaisjp** [comment]
Unfortunately we can't merge the duplicated clause now, but we can merge the single quote fix. Might be better to split and merge the quote fixes separately?

**Comment by qaisjp** [comment]
Also, it being merged doesn't mean it's part of the constitution — just means we don't need to worry about voting it in as we'll quote it as "General stylistic changes" (refer to one of the previous releases)

**Comment by JMaio** [comment]
commit to fix #15 reverted, single quote fix still present

**Comment by qaisjp** [comment]
The package import `textcomp` was required for the single quote stuff so that can now be removed.

**Comment by qaisjp** [comment]
Please submit a new pull request @JMaio as it looks like @findoslice prematurely merged...

**Comment by himmelmaus** [comment]
Sorry, didn't notice the package import

**Pull request merged**
