### PR TITLE
Typos and clarifications

### PR DESCRIPTION
**Pull request by penalosa**
Under 4.10 (b), this is a suggested change to the amended constitution to be voted on Friday

### CODE REVIEW

**Review by RyanT5 — APPROVED** [review]
Pre-approved, pending AGM vote

**Review by alexandrapurcarea — APPROVED** [review]

**Comment by alexandrapurcarea** [comment]
Can someone else approve this as well?

**Review by yutotakano — APPROVED** [review]
Approved.

**Comment by tcmal** [comment]
Closing this for inactivity, but I think it should be covered between #33 and #31

**Pull request closed without merging**
