### PR TITLE
add Co-President position

### PR DESCRIPTION
**Pull request by Riotshielder21**
add possibility for dual presidency in the constitution found in committee.tex

### CODE REVIEW

**Comment by qaisjp** [comment]
Hey! Committee member here.

In my opinion, this is a _very_ good idea. Unfortunately, it is a bit late and this is something you will have to bring up ahead of the October EGM.

There is a 2 week notice for the _committee_ to inform members about constitution amendments, which means even more notice is needed for the committee to vote in your amendment for consideration at an AGM/EGM.

> for the committee to vote in your amendment for consideration at an AGM/EGM

I actually do not know if this is required, or if individuals can propose amendments directly to members at an GM. Nevertheless, at least 2 weeks (14 days) notice is still required for members to be informed.

All in all, personally, I am very much in support of your proposal!

**Comment by mojavad** [comment]
Hey! 

I think that this proposed change is a bit ridiculous if I'm being completely frank. 

We already have a VP position in order to address some of the responsibilities that would have fallen onto the president (or other committee members) otherwise. I don't see the benefit of having the option to have co-presidents other than letting friends run together...

I think that giving the option to have co-presidents alongside an already present vice-president (or potential co-vice-presidents if you want to go even further) is just unnecessary. 

I am, however, for the addition of new committee positions; ones that are specialized in specific areas and have some of the responsibilities that are currently being done by the committee delegated to them (such as a designer, or librarian role).

**Comment by mojavad** [comment]
I also think that having: 
> At the end of each month, the positions of President and Co-President shall switch or Current President may choose to at any other time. 

is a weird delegation and division of work.

**Comment by himmelmaus** [comment]
Ok so having looked this over, I'm mostly in agreement with @mojavad. I think in theory that delegating some responsibilities away from the president are a good idea, but a co president solution definitely.is not the way to go to accomplish that imo. 

I think that having a co president role would just cause confusion with sponsors and general running of the society, as well as causing a lot of friction around the time of the handovers.

That being said, don't be discouraged from suggesting ideas like these @Riotshielder21. Id highly recommend you come along to our next committee meeting to discuss your motivation for this, as new committee positions are something we've been discussing a lot recently.

**Comment by qaisjp** [comment]
Looking at the actual commit content in detail I agree some work needs to be done.

Here's an excerpt from PrideSoc's constitution, which I think executes it in a way that doesn't undermine the Vice-President position.


image


I agree with the others that the current implementation in this PR is lacking.

**Comment by JMaio** [comment]
To reiterate, vice-president is already a role, and co-presiding is probably not necessary. Having other committee positions would help diversify the committee in terms of responsibility though, and is something we have looked into and considered recently. This is an approach which would maintain the general state of things while offering extra support, so is likely ideal in place of co-presiding the society.

**Comment by pkage** [comment]
Closing due to group consensus.

**Comment by himmelmaus** [comment]
@pkage pls don't close PRs where active discussion is happening, especially r.e. the constitution (despite being on github) isn't technically techsec's jurisdiction. 

While I don't think co presidency specifically is ever going to be feasible the discussion will likely be productive. I think we also need more input from @Riotshielder21 .

**Comment by Riotshielder21** [comment]
There is definitely a lot to think about, the idea initially came about due to the amount of work such a small committee had to do for such a large society.
are there other solutions that would work by adding new roles to the society?

**Pull request closed without merging**
